/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package usuarios;

/**
 *
 * @author Marcos
 */
public class Painel_Senha_Administrador extends javax.swing.JPanel {

    /**
     * Creates new form Painel_Senha_Administrador
     */
    public Painel_Senha_Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();

        setLayout(null);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSenha.setText("Digite a senha do administrador!");
        add(lblSenha);
        lblSenha.setBounds(30, 30, 210, 15);

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(txtSenha);
        txtSenha.setBounds(30, 50, 200, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblSenha;
    public javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
